routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Cabinet\CabinetCourseController;
use App\Http\Controllers\Cabinet\CabinetMaterialController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Cabinet\CabinetController;
use App\Http\Controllers\RatingTeacherController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth'])->group(function () {

    // личные кабинеты
    Route::prefix('cabinet')->group(function () {
        Route::get('index', [CabinetController::class, 'index'])->name('cabinet.index');
        Route::get('edit', [CabinetController::class, 'edit'])->name('cabinet.edit');
        Route::put('update', [CabinetController::class, 'update'])->name('cabinet.update');

        //    курсы
        Route::resource('course', CabinetCourseController::class)->only(['show', 'edit', 'create', 'store', 'destroy']);

        //      теор.материал для курса
        Route::resource('course.material', CabinetMaterialController::class)->only(['show', 'update', 'edit', 'create', 'store', 'destroy']);
    });

        //        рейтинг учителя
    Route::prefix('rating-teacher')->group(function () {
        Route::get('', [RatingTeacherController::class, 'index'])->name('rating-teacher.index');
        Route::get('{user}/rate', [RatingTeacherController::class, 'rate'])->name('rating-teacher.rate');
        Route::post('{user}/rate', [RatingTeacherController::class, 'saveRate'])->name('rating-teacher.save-rate');
    });
});


require __DIR__ . '/auth.php';

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
], function () {
    Route::get('', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('user', UserController::class);
});

resources/views/admin/layouts/includes/footer.blade.php
<footer class="footer">
{{--    --}}
</footer>

resources/views/admin/layouts/includes/header.blade.php
<header class="header header-sticky mb-4">
    <div class="container-fluid">
        <button class="header-toggler px-md-0 me-md-3" type="button" onclick="coreui.Sidebar.getInstance(document.querySelector('#sidebar')).toggle()">
            <svg class="icon icon-lg">
                <use xlink:href="node_modules/@coreui/icons/sprites/free.svg#cil-menu"></use>
            </svg>
        </button><a class="header-brand d-md-none" href="#">
            <svg width="118" height="46" alt="CoreUI Logo">
                <use xlink:href="assets/brand/coreui.svg#full"></use>
            </svg></a>
        <ul class="header-nav d-none d-md-flex">
            <li class="nav-item">
                    <form class="btn btn-warning" method="POST" action="{{ route('logout') }}">
                        @csrf
                        <x-responsive-nav-link :href="route('logout')"
                                               onclick="event.preventDefault();
                                        this.closest('form').submit();">
                            {{ __('Вийти') }}
                        </x-responsive-nav-link>
                    </form>
            </li>
        </ul>
        <ul class="header-nav ms-auto">
            <li class="nav-item"><a class="nav-link" href="#">
                    <svg class="icon icon-lg">
                        <use xlink:href="node_modules/@coreui/icons/sprites/free.svg#cil-bell"></use>
                    </svg></a></li>
            <li class="nav-item"><a class="nav-link" href="#">
                    <svg class="icon icon-lg">
                        <use xlink:href="node_modules/@coreui/icons/sprites/free.svg#cil-list-rich"></use>
                    </svg></a></li>
            <li class="nav-item"><a class="nav-link" href="#">
                    <svg class="icon icon-lg">
                        <use xlink:href="node_modules/@coreui/icons/sprites/free.svg#cil-envelope-open"></use>
                    </svg></a></li>
        </ul>
        <ul class="header-nav ms-3">
            <li class="nav-item dropdown"><a class="nav-link py-0" data-coreui-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    <div class="avatar avatar-md"><img class="avatar-img" src="" alt=""></div></a>
                <div class="dropdown-menu dropdown-menu-end pt-0">
                    <div class="dropdown-header bg-light py-2">
                        <div class="fw-semibold">Account</div>
                    </div><a class="dropdown-item" href="#">
                        <svg class="icon me-2">
                            <use xlink:href="node_modules/@coreui/icons/sprites/free.svg#cil-bell"></use>
                        </svg> Updates<span class="badge badge-sm bg-info ms-2">42</span></a><a class="dropdown-item" href="#">
                        <svg class="icon me-2">
                            <use xlink:href="node_modules/@coreui/icons/sprites/free.svg#cil-envelope-open"></use>
                        </svg> Messages<span class="badge badge-sm bg-success ms-2">42</span></a><a class="dropdown-item" href="#">
                        <svg class="icon me-2">
                            <use xlink:href="node_modules/@coreui/icons/sprites/free.svg#cil-task"></use>
                        </svg> Tasks<span class="badge badge-sm bg-danger ms-2">42</span></a><a class="dropdown-item" href="#">
                        <svg class="icon me-2">
                            <use xlink:href="node_modules/@coreui/icons/sprites/free.svg#cil-comment-square"></use>
                        </svg> Comments<span class="badge badge-sm bg-warning ms-2">42</span></a>
                    <div class="dropdown-header bg-light py-2">
                        <div class="fw-semibold">Settings</div>
                    </div><a class="dropdown-item" href="#">
                        <svg class="icon me-2">
                            <use xlink:href="node_modules/@coreui/icons/sprites/free.svg#cil-user"></use>
                        </svg> Profile</a><a class="dropdown-item" href="#">
                        <svg class="icon me-2">
                            <use xlink:href="node_modules/@coreui/icons/sprites/free.svg#cil-settings"></use>
                        </svg> Settings</a><a class="dropdown-item" href="#">
                        <svg class="icon me-2">
                            <use xlink:href="node_modules/@coreui/icons/sprites/free.svg#cil-credit-card"></use>
                        </svg> Payments<span class="badge badge-sm bg-secondary ms-2">42</span></a><a class="dropdown-item" href="#">
                        <svg class="icon me-2">
                            <use xlink:href="node_modules/@coreui/icons/sprites/free.svg#cil-file"></use>
                        </svg> Projects<span class="badge badge-sm bg-primary ms-2">42</span></a>
                    <div class="dropdown-divider"></div><a class="dropdown-item" href="#">
                        <svg class="icon me-2">
                            <use xlink:href="node_modules/@coreui/icons/sprites/free.svg#cil-lock-locked"></use>
                        </svg> Lock Account</a><a class="dropdown-item" href="#">
                        <svg class="icon me-2">
                            <use xlink:href="node_modules/@coreui/icons/sprites/free.svg#cil-account-logout"></use>
                        </svg> Logout</a>
                </div>
            </li>
        </ul>
    </div>
{{--    <div class="header-divider"></div>--}}
{{--    <div class="container-fluid">--}}
{{--        <nav aria-label="breadcrumb">--}}
{{--            <ol class="breadcrumb my-0 ms-2">--}}
{{--                <li class="breadcrumb-item">--}}
{{--                    <!-- if breadcrumb is single--><span>Home</span>--}}
{{--                </li>--}}
{{--                <li class="breadcrumb-item active"><span>Dashboard</span></li>--}}
{{--            </ol>--}}
{{--        </nav>--}}
{{--    </div>--}}
</header>

resources/views/admin/layouts/includes/sidebar.blade.php
<div class="sidebar sidebar-dark sidebar-fixed" id="sidebar">
    <div class="sidebar-brand d-none d-md-flex">
        <a class="nav-link nav-group-toggle text-white" href="/">
            На головну сторінку сайту
        </a>

    </div>
    <ul class="sidebar-nav" data-coreui="navigation" data-simplebar>
        {{--        верхний элемент sidebar--}}
        <li class="nav-item"><a class="nav-link" href="{{ route('admin.dashboard') }}">
                Головна сторінка адмінки</a>
        </li>

        <li class="nav-group">
            <a class="nav-link nav-group-toggle" href="">
                Користувачі
            </a>
            <ul class="nav-group-items">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('admin.user.index', ['role'=>'admin'])}}" target="_top">
                        <i class="fa-solid fa-street-view me-2"></i>
                        Адміністратори
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('admin.user.index',['role'=>'teacher'])}}" target="_top">
                        <i class="fa-solid fa-chalkboard-user me-2"></i>Вчителі
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('admin.user.index',['role'=>'student'])}}" target="_top">
                        <i class="fa-solid fa-graduation-cap me-2"></i>
                        Учні
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('admin.user.index',['role'=>''])}}" target="_top">
                        <i class="fa-solid fa-users me-2"></i>
                        Показати всіх
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ route('admin.user.create') }}" target="_top">
                        <i class="fas fa-user-plus me-2"></i>
                        Додати користувача
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</div>