routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Cabinet\CabinetCourseController;
use App\Http\Controllers\Cabinet\CabinetMaterialController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Cabinet\CabinetController;
use App\Http\Controllers\RatingTeacherController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth'])->group(function () {

    // личные кабинеты
    Route::prefix('cabinet')->group(function () {
        Route::get('index', [CabinetController::class, 'index'])->name('cabinet.index');
        Route::get('edit', [CabinetController::class, 'edit'])->name('cabinet.edit');
        Route::put('update', [CabinetController::class, 'update'])->name('cabinet.update');

        //    курсы
        Route::resource('course', CabinetCourseController::class)->only(['show', 'edit', 'create', 'store', 'destroy']);

        //      теор.материал для курса
        Route::resource('course.material', CabinetMaterialController::class)->only(['show', 'update', 'edit', 'create', 'store', 'destroy']);
    });

        //        рейтинг учителя
    Route::prefix('rating-teacher')->group(function () {
        Route::get('', [RatingTeacherController::class, 'index'])->name('rating-teacher.index');
        Route::get('{user}/rate', [RatingTeacherController::class, 'rate'])->name('rating-teacher.rate');
        Route::post('{user}/rate', [RatingTeacherController::class, 'saveRate'])->name('rating-teacher.save-rate');
    });
});


require __DIR__ . '/auth.php';

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
], function () {
    Route::get('', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('user', UserController::class);
});

app/Models/Course.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Course extends Model
{
    use HasFactory, HasSlug;

    protected $fillable = [
        'category_id', 'user_teacher_id', 'name', 'description'
    ];

    protected $table = 'сourses';
    /**
     * Get the options for generating the slug.
     */
    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('name')
            ->saveSlugsTo('slug');
    }

    public function category()
    {
        return $this->belongsTo(Category::class,'category_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function courseMaterials()
    {
        return $this->hasMany(CourseMaterial::class);
    }

    public function courseRatings()
    {
        return $this->belongsToMany(CourseRatings::class, 'courses_rating_courses');
    }
}

app/Http/Controllers/Cabinet/CabinetMaterialController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Http\Controllers\Controller;
use App\Models\Course;
use App\Models\CourseMaterial;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class CabinetMaterialController extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create(Course $course)
    {
        return view('course.cabinet-material.create', ['course' => $course]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @param Course $course
     * @return Response
     */
    public function store(Request $request, Course $course)
    {
        $material = new CourseMaterial();
        $material->fill($request->all());
        $material->course_id = $course->id;
        $material->save();

        return redirect()->route('course.show', $course->slug);
    }

    /**
     * Display the specified resource.
     *
     * @param Course $course
     * @param CourseMaterial $material
     * @return Response
     */
    public function show(Course $course, CourseMaterial $material)
    {
        dd('show - CabinetMaterialController');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Course $course
     * @param CourseMaterial $material
     * @return Response
     */
    public function edit(Course $course, CourseMaterial $material)
    {
        return view('course.cabinet-material.edit', [
            'course' => $course,
            'material' => $material
        ]);
//        return redirect()->route('course.show', $course->slug)->withFlashSuccess("Блок $material->name, змінено");

    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Course $course
     * @param CourseMaterial $material
     * @return Response
     */
    public function update(Request $request, Course $course, CourseMaterial $material)
    {
        $material->fill($request->all());
        $material->save();
        return redirect()->route('course.show', $course->slug)->withFlashSuccess("Блок $material->name, змінено");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Course $course
     * @param CourseMaterial $material
     * @return Response
     */
    public function destroy(Course $course, CourseMaterial $material)
    {
        $name = $material->name;
        $material->delete();
        return redirect()->route('course.show', $course->slug)->withFlashSuccess("Блок $name, видалено");
    }
}

resources/views/course/cabinet-material/create.blade.php
@extends('cabinet.sample')
@section('content')
    <div class="container" >
        <h4 class="text-center me-2">Додати блок теорії до цього курсу</h4>
        <form class="w-50" enctype="multipart/form-data" method="post"
              action="{{ route('course.material.store', $course) }}">
            @csrf
            {{--name--}}
            <div class="form-group mb-3">
                <label for="inputName">Назва блоку</label>
                <input name="name" class="form-control @error('name') is-invalid @enderror"
                       id="inputName" type="text"
                       value="{{ old('name')}}"
                       placeholder="Назва блоку">
                @error('name')
                <span class="alert-danger">{{ $message }}</span>
                @enderror
            </div>
            {{-- description--}}
            <div class="form-group mb-3">
                <label for="inputName">Матеріал теоретичного блоку</label>
                <input name="description" class="form-control @error('description') is-invalid @enderror"
                       id="inputDescription" type="text"
                       value="{{ old('description')}}" placeholder="Матеріал теоретичного блоку">
                @error('description')
                <span class="alert-danger">{{ $message }}</span>
                @enderror
            </div>
            <button class="btn btn-primary" type="submit">Додати</button>
        </form>
    </div>
@endsection

resources/views/course/cabinet-material/edit.blade.php
@extends('cabinet.sample')
@section('content')
    <div class="container" >
        <h4 class="text-center me-2">Додати блок теорії до цього курсу</h4>
        <form class="w-50" enctype="multipart/form-data" method="post"
              action="{{ route('course.material.update', [$course, $material]) }}">
            @csrf
            @method('PUT')
            {{--name--}}
            <div class="form-group mb-3">
                <label for="inputName">Назва блоку</label>
                <input name="name" class="form-control @error('name') is-invalid @enderror"
                       id="inputName" type="text"
                       value="{{ old('name') ?? $material->name}}"
                       placeholder="Назва блоку">
                @error('name')
                <span class="alert-danger">{{ $message }}</span>
                @enderror
            </div>
            {{-- description--}}
            <div class="form-group mb-3">
                <label for="inputName">Матеріал теоретичного блоку</label>
                <input name="description" class="form-control @error('description') is-invalid @enderror"
                       id="inputDescription" type="text"
                       value="{{ old('description') ?? $material->description}}" placeholder="Матеріал теоретичного блоку">
                @error('description')
                <span class="alert-danger">{{ $message }}</span>
                @enderror
            </div>
            <button class="btn btn-primary" type="submit">Додати</button>
        </form>
    </div>
@endsection