routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Cabinet\CabinetCourseController;
use App\Http\Controllers\Cabinet\CabinetMaterialController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Cabinet\CabinetController;
use App\Http\Controllers\RatingTeacherController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth'])->group(function () {

    // личные кабинеты
    Route::prefix('cabinet')->group(function () {
        Route::get('index', [CabinetController::class, 'index'])->name('cabinet.index');
        Route::get('edit', [CabinetController::class, 'edit'])->name('cabinet.edit');
        Route::put('update', [CabinetController::class, 'update'])->name('cabinet.update');

        //    курсы
        Route::resource('course', CabinetCourseController::class)->only(['show', 'edit', 'create', 'store', 'destroy']);

        //      теор.материал для курса
        Route::resource('course.material', CabinetMaterialController::class)->only(['show', 'update', 'edit', 'create', 'store', 'destroy']);
    });

        //        рейтинг учителя
    Route::prefix('rating-teacher')->group(function () {
        Route::get('', [RatingTeacherController::class, 'index'])->name('rating-teacher.index');
        Route::get('{user}/rate', [RatingTeacherController::class, 'rate'])->name('rating-teacher.rate');
        Route::post('{user}/rate', [RatingTeacherController::class, 'saveRate'])->name('rating-teacher.save-rate');
    });
});


require __DIR__ . '/auth.php';

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
], function () {
    Route::get('', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('user', UserController::class);
});

app/Models/Traits/HasImage.php
<?php


namespace App\Models\Traits;

use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;

trait HasImage
{
    public function getImageUrlAttribute()
    {
        return !empty($this->image) ? Storage::url($this->image) : '/img/no-image.jpg';
    }

    public function uploadImage(UploadedFile $imageFile) {

        $this->deleteImage();
        $fileName = md5(time()).'.'.$imageFile->getClientOriginalExtension();
        $this->image = $imageFile->storeAs('uploads', $fileName,  'public');
    }

    public function deleteImage()
    {
        if(!empty($this->image) && Storage::exists($this->image)){
            Storage::delete($this->image);
        }
        $this->image = null;
    }
}

app/Models/User.php
<?php

namespace App\Models;

use App\Models\Traits\HasImage;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasImage;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'surname',
        'patronymic',
        'email',
        'phone',
        'image',
        'work_place',
        'school_class',
        'rating',
        'password',
        'remember_token',
        'email_verified_at'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $appends = [
        'image_url',
    ];

    public function courses()
    {
        return $this->hasMany(Course::class);
    }
    public function roles()
    {
        return $this->belongsToMany(Role::class, 'user_role');
    }

    public function students()
    {
        return $this->belongsToMany(User::class, 'ratings_teachers', 'student_id', 'teacher_id');
    }

    public function teachers()
    {
        return $this->belongsToMany(User::class, 'ratings_teachers', 'teacher_id', 'student_id')->withPivot('rating');
    }

    public function hasRoles(...$roles)
    {
        foreach ($roles as $role) {
            if ($this->roles->where('name', '=', $role)->count() > 0) {
                return true;
            }
            return false;
        }
    }

    public function getRatingAttribute()
    {
        return  DB::table('ratings_teachers')->where('teacher_id', $this->id)->avg('rating') ?? 0;
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\User\UserStoreRequest;
use App\Models\Role;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(Request $request)
    {
        $usersQ = User::query();

        $role = $request->input('role', '');
        if (!empty($role)) {
            $usersQ->whereHas('roles', fn($q) => $q->where('name', $role));
        }

        return view('admin.user.index', [
            'users' => $usersQ->paginate(6),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create()
    {

        $user = new User();
        return view('admin.user.create', [
            'user' => $user,
            'roles' => Role::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserStoreRequest $request)
    {
dd('store');
//        $user = User::create([
//            'name' => $request->name,
//            'surname' => $request->surname,
//            'patronymic' => $request->patronymic,
//            'email' => $request->email,
//            'phone' => $request->phone,
//            'password' => Hash::make($request->password), // 123456789
//            'email_verified_at' => now(),
//            'remember_token' => Str::random(10),
//        ]);

//        $roleIds = Role::whereIn('name', $request->role)->get()->pluck('id')->toArray();
//        $user->roles()->sync($roleIds);
//        $data = $request->except(['_token', '_method', 'role']);
        $user->fill($request->all());
        if ($request->hasFile('image_upload')) {
            $user->uploadImage($request->file('image_upload'));
        }
        $user->save();


        $roleIds = Role::whereIn('name', $request->role)->get()->pluck('id')->toArray();
        $user->roles()->sync($roleIds);
        return redirect()->route('admin.user.index')->withFlashSuccess("Пользователь $request->name добавлен");
    }

    /**
     * Display the specified resource.
     *
     * @param User $user
     * @return View
     */
    public function show(User $user)
    {
        return view('admin.user.show', [
            'user' => $user,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return View
     */

    public function edit(User $user)
    {
        $userRoles = $user->roles->pluck('name')->toArray();
        $roles = Role::all();

        return view('admin.user.edit', [
            'user' => $user,
            'roles' => $roles,
            'userRoles' => $userRoles,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        /*
        $user = Auth::user();
        $user->fill($request->all());
        if($request->hasFile('image_upload')){
            $user->uploadImage($request->file('image_upload'));
        }
        $user->save();
        */

        $roleIds = Role::whereIn('name', $request->role)->get()->pluck('id')->toArray();
        $user->roles()->sync($roleIds);
//        $data = $request->except(['_token', '_method', 'role']);
        $user->fill($request->all());
        if ($request->hasFile('image_upload')) {
            $user->uploadImage($request->file('image_upload'));
        }
        $user->save();

        return redirect()->route('admin.user.index')->withFlashSuccess("Користувач $user->name  змінено");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $name = $user->name;
        $user->delete();
        return redirect()->route('admin.user.index')->withFlashSuccess("Пользователь $name  добавлен");
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <form class="row g-3" enctype="multipart/form-data" method="post" action="{{ route('admin.user.store') }}">
        @csrf
        @include('admin.user.includes.form')

        {{-- button--}}
        <div class="form-group w-20">
            <button class="btn btn-primary" type="submit">Додати</button>
        </div>
    </form>
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.app')

@section('content')

    <form class="row g-3" enctype="multipart/form-data" method="post" action="{{route('admin.user.update',$user)}}">
        @csrf
        @method('put')
        @include('admin.user.includes.form')

        {{-- button--}}
        <div class="form-group w-20">
            <button class="btn btn-primary" type="submit">Зберегти</button>
        </div>
    </form>

@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="example">
        @if (session()->has('flash_success'))
            <div class="toast-body bg-success text-white">
                {{ session()->get('flash_success') }}
            </div>
        @endif

        <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item"><a class="nav-link active" data-coreui-toggle="tab" href="#preview-595" role="tab">
                    <svg class="icon me-2">
                        <use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-media-play"></use>
                    </svg>
                    Preview</a></li>
            <li class="nav-item"><a class="nav-link" data-coreui-toggle="tab" href="#code-595" role="tab">
                    <svg class="icon me-2">
                        <use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-code"></use>
                    </svg>
                    Code</a></li>
        </ul>
        <div class="tab-content rounded-bottom">
            <div class="tab-pane p-3 active preview" role="tabpanel" id="preview-595">
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Прізвище</th>
                        <th scope="col">Ім'я</th>
                        <th scope="col">Фото</th>
                        <th scope="col">Статус</th>
                        <th scope="col">Дії</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $user)
                        <tr>
                            <th scope="row">{{ $user['id'] }}</th>
                            <td>{{ $user['surname'] }}</td>
                            <td>{{ $user['name'] }}</td>
                            <td>
                                <img style="height: 50px;" src="{{ $user->image_url }}" alt="">
                            </td>
                            <td>
                                @foreach($user->roles as $role)
                                    {{$role['description']}}
                                @endforeach
                            </td>
                            <td>
                                <div class="row justify-content-center">
                                    <div class="col-5">
                                        <a class="col btn btn-success"
                                           href="{{ route('admin.user.edit', $user)}}">
                                            <i class="fa-solid fa-pen-to-square"></i>
                                            Змінити</a>
                                    </div>
                                    <div class="col-5">
                                        <form class="col"
                                              action="{{ route('admin.user.destroy', $user)}}"
                                              method="post">
                                            @csrf
                                            @method('delete')
                                            <button class="ml-3 btn btn-danger" type="submit">
                                                <i class="fa-solid fa-trash-can"></i>
                                                Вилучити
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    @endforeach

                    </tbody>
                </table>
                {{$users->links()}}
            </div>

            <div class="tab-pane pt-1" role="tabpanel" id="code-595">
                sdsf
            </div>
        </div>
    </div>
@endsection