routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Cabinet\CabinetCourseController;
use App\Http\Controllers\Cabinet\CabinetMaterialController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Cabinet\CabinetController;
use App\Http\Controllers\RatingTeacherController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth'])->group(function () {

    // личные кабинеты
    Route::prefix('cabinet')->group(function () {
        Route::get('index', [CabinetController::class, 'index'])->name('cabinet.index');
        Route::get('edit', [CabinetController::class, 'edit'])->name('cabinet.edit');
        Route::put('update', [CabinetController::class, 'update'])->name('cabinet.update');

        //    курсы
        Route::resource('course', CabinetCourseController::class)->only(['show', 'edit', 'create', 'store', 'destroy']);

        //      теор.материал для курса
        Route::resource('course.material', CabinetMaterialController::class)->only(['show', 'update', 'edit', 'create', 'store', 'destroy']);
    });

        //        рейтинг учителя
    Route::prefix('rating-teacher')->group(function () {
        Route::get('', [RatingTeacherController::class, 'index'])->name('rating-teacher.index');
        Route::get('{user}/rate', [RatingTeacherController::class, 'rate'])->name('rating-teacher.rate');
        Route::post('{user}/rate', [RatingTeacherController::class, 'saveRate'])->name('rating-teacher.save-rate');
    });
});


require __DIR__ . '/auth.php';

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
], function () {
    Route::get('', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('user', UserController::class);
});

app/Models/Course.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Course extends Model
{
    use HasFactory, HasSlug;

    protected $fillable = [
        'category_id', 'user_teacher_id', 'name', 'description'
    ];

    protected $table = 'сourses';
    /**
     * Get the options for generating the slug.
     */
    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('name')
            ->saveSlugsTo('slug');
    }

    public function category()
    {
        return $this->belongsTo(Category::class,'category_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function courseMaterials()
    {
        return $this->hasMany(CourseMaterial::class);
    }

    public function courseRatings()
    {
        return $this->belongsToMany(CourseRatings::class, 'courses_rating_courses');
    }
}

resources/views/course/show.blade.php
@extends('cabinet.sample')
@section('content')


    <div class="container">
        <h2 class="text-center mb-5">Курс {{ $course->name }}</h2>
        <div class="row">
            @if (session()->has('flash_success'))
                <div class="toast-body bg-success text-white">
                    {{ session()->get('flash_success') }}
                </div>
            @endif
            <div class="col-4 p-3 mb-2 bg-secondary text-white">
                <p>Короткий опис курсу: <br>{{ $course->description }}</p>
                <hr>
                <a href="{{ route('course.material.create', $course) }}" class="btn btn-primary">
                    Створити блок теорії
                </a>
                <a href="{{ route('cabinet.index') }}" class="btn btn-primary">
                    Усі мої курси
                </a>
            </div>
            <div class="col">
                <h3 class="text-center mb-2">Теоретичний матеріал</h3>
                <hr>
                @foreach($courseMaterials as $item)
                    <p>Назва блоку: {{ $item->name }}</p>
                    <p>Зміст: {{ $item->description}}</p>
                    <div class="row">
                        <div class="col">
                            <a class="btn btn-success"
                               href="{{route('course.material.edit', [$course, $item])}}">
                                <i class="fa-solid fa-pen-to-square"></i>
                                Змінити</a>
                        </div>
                        <div class="col">
                            <form action="{{route('course.material.destroy', [$course, $item])}}"
                                  method="post">
                                @csrf
                                @method('delete')
                                <button class="ml-3 btn btn-danger" type="submit">
                                    Вилучити
                                </button>
                            </form>
                        </div>
                    </div>
                    <hr>
                @endforeach
            </div>
        </div>
    </div>
@endsection